version: '3'

services:
  pixelartmaker:
    image: lstz/pixelartmaker:latest
    ports:
      - '3100:3100'
    networks:
      - pixelartmaker-networks

networks:
  pixelartmaker-networks:
    external: true
